<?php
    header("Access-Control-Allow-Origin: *");
    header('Access-Control-Allow-Headers: Content-Type');

    /*
     *
     * Do not edit this file if you want to update this module for future new versions.
     *
     * @class  SearchPerson
     * @package   Api_SearchPerson
     *
     * @copyright Copyright (c) 2023 McFadyen Digital.
     *
     * @author    Athira Indrakumar<athiraindrakumar396@gmail.com>
     *
     */
    class SearchPerson {

        /**
         * execute people filtering api with filter param as the person's name
         **/
        public function searchPersonApi() {
            $request_body = file_get_contents('php://input');
            $data = json_decode($request_body, true);
            $item = $data['item'];

            $curl = curl_init();
            curl_setopt($curl, CURLOPT_URL, "https://swapi.dev/api/people/?search=" . $item);
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
            $output = curl_exec($curl);
            curl_close($curl);

            $people = array();
            if ($output) {
                foreach(json_decode($output, true)['results'] as $person) {
                    $people[] = $person;
                }
            }
            echo json_encode($people);
        }
    }

    $person = new SearchPerson();
    $person->searchPersonApi();
?>