<?php
    header("Access-Control-Allow-Origin: *");
    header('Access-Control-Allow-Headers: Content-Type');

    /*
     *
     * Do not edit this file if you want to update this module for future new versions.
     *
     * @class  ViewPlanet
     * @package   Api_ViewPlanet
     *
     * @copyright Copyright (c) 2023 McFadyen Digital.
     *
     * @author    Athira Indrakumar<athiraindrakumar396@gmail.com>
     *
     */
    class ViewPlanet {

        /**
         * execute planet viewing api
         **/
        public function callPlanetsApi() {
            $request_body = file_get_contents('php://input');
            $data = json_decode($request_body, true);
            $id = ltrim(rtrim($data['planetId'], '/'), 'https://swapi.dev/api/planets/');

            $curl = curl_init();
            curl_setopt($curl, CURLOPT_URL, "https://swapi.dev/api/planets/" . $id);
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
            $output = curl_exec($curl);
            curl_close($curl);

            $result = array(json_decode($output, true));
            echo json_encode($result);
        }
    }

    $planet = new ViewPlanet();
    $planet->callPlanetsApi();
?>