<?php
    header("Access-Control-Allow-Origin: *");
    header('Access-Control-Allow-Headers: Content-Type');

    /*
     *
     * Do not edit this file if you want to update this module for future new versions.
     *
     * @class  ViewStarships
     * @package   Api_ViewStarships
     *
     * @copyright Copyright (c) 2023 McFadyen Digital.
     *
     * @author    Athira Indrakumar<athiraindrakumar396@gmail.com>
     *
     */
    class ViewStarships {

        /**
         * execute starships viewing api
         **/
        public function callStarshipsApi() {
            $request_body = file_get_contents('php://input');
            $data = json_decode($request_body, true);
            $id = ltrim(rtrim($data['starshipId'], '/'), 'https://swapi.dev/api/starships/');

            $curl = curl_init();
            curl_setopt($curl, CURLOPT_URL, "https://swapi.dev/api/starships/" . $id);
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
            $output = curl_exec($curl);
            curl_close($curl);

            $result = array(json_decode($output, true));
            echo json_encode($result);
        }
    }

    $starships = new ViewStarships();
    $starships->callStarshipsApi();
?>